# Generated by Django 3.2 on 2021-04-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('decs', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
