# Generated by Django 3.2 on 2021-05-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cname',
            new_name='name',
        ),
    ]
