# Generated by Django 3.2 on 2021-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cartdecs',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='cartimage',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cartname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
