# Generated by Django 3.2 on 2021-05-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210501_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartimage',
            field=models.ImageField(default='', upload_to='shop/cartimage'),
        ),
    ]
