# Generated by Django 3.2 on 2021-05-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_cart_cartimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cartprice',
            field=models.IntegerField(default=0),
        ),
    ]
