# Generated by Django 3.2 on 2021-05-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart_cartprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(default='', max_length=50)),
                ('loginname', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
